version: '3.1'
services:
  mongo:
    image: mongo:latest
    container_name: pr32_websocket_link_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db


  mongo-express:
    image: mongo-express:latest
    container_name: pr32_websocket_link_mongo_websockets
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: "mongodb://root:password@pr32_websocket_link:27017/"

  loki:
    image: grafana/loki:latest
    container_name: pr32_websocket_link_loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki-data:/loki

  grafana:
    image: grafana/grafana:latest
    container_name: pr32_websocket_link_grafana
    depends_on:
      - loki
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  mongo-data:
  loki-data:
  grafana-data:
